### ISSUE TITLE
Add flair flag for tags

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#73]
# Motivation
Need this for AI flair

# Tasks
- [x] Rework the tag struct to accept arbitrary metadata
- [x] Add generic AI Flair with sparkles
- [x] Update autocompletion to update the AI tag
