### ISSUE TITLE
Clerk migration

### ISSUE THREAD

**Issue by daryllimyt** [TracecatHQ/tracecat#95]
# Motivation
1. Supabase auth isn't robust enough for our usage. Move to Clerk.
2. Supabase auth primitives are quite low-level and a lot of the authentication logic has to be managed directly by us
3. Handling sessions and middleware is cumbersome

# Implementation
- Leverage middleware to decouple auth logic from application logic
  - This means we should only use redirects where necessary
- Use Axios interceptors to apply authentication for all backend requests
- Offload onboarding and new user flow responsibilities to custom Clerk `publicMetadata` for each user, and handled within a `/onboarding` component

# Tasks
- [x] Migrate sign in/up page
  - [x] Replaced these with Clerk builtins
- [x] Migrate `middleware.ts`
- [x] Migrate all `supabase.auth` usage to Clerk alternative
- [x] Update onboarding flow (creating first workflow) to use Clerk onboarding middleware
- [x] Update FastAPI backend
  - [x] Update fastapi auth dependencies?
  - [x] How to handle authing sessions
  - [x] [v0] No need to replace Supabase as a DB provider, but decouple Supabase dependency
  - [ ] [v1] Replace supabase with generic postgres
- [x] Allow passing of `TRACECAT__DISABLE_AUTH` build flag to disable auth
  - [x] This works nicely because we've centralized (almost) all auth logic into the Axios interceptor. We can conditionally apply the authenticated interceptor at application startup.
  - [x] Update backend to change authentication strategy based on `TRACECAT__DISABLE_AUTH` flag
